### ISSUE TITLE
泛型有什么优势？

### ISSUE THREAD

**Issue by taoso** [daodao97/ggm#1]
没有泛型的写法
```golang
var list []*User
_ = db.Query(sql, &list)
```
你的写法
```golang
list, _ := ggm.New[User]().Select(sql)
```

这两种也没有本质的区别呀。性能上没有任何优势，而且使用泛型还会拖慢编译速度，增加理解成本。

**Comment by daodao97** [comment]
确实没有本质区别, 这里的优势也仅限于, 拿到的结果 `list` 不用定义就是拥有特定类型的.

目前看泛型应该会在 `lodash` 类的工具函数中广泛应用.

新事物嘛也要积极尝试, Just for fun.
