### ISSUE TITLE
是否支持根据struct创建表以及同步表？

### ISSUE THREAD

**Issue by calvin2021y** [daodao97/ggm#2]
是否支持根据struct创建表以及同步表？

**Comment by daodao97** [comment]
1. 暂未支持根据 struct 创建表,  在绝大部分公司中的数据库操作要由dba审核等流程才能创建/更改, ggm目前还是聚焦到业务层的使用场景
2. 同步表是指 表之间的数据同步吗, 可以使用 [canal](https://github.com/alibaba/canal)
